name: Excercise 10

on:
  push:
    paths:
      - "ex10/**/*.py"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup GCC multilib
        run: sudo apt install -y gcc-multilib
      - name: Task 1 tests
        run: python3 -m unittest -v
        working-directory: ex10
