name: Excercise 11

on:
  push:
    paths:
      - "ex11/**/*.py"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Task 1 tests
        run: python3 -m unittest -v
        working-directory: ex11
